### ISSUE TITLE
JSS URL: Unable to Connect with trailing slash

### ISSUE THREAD

**Issue by talkingmoose** [jamf/HealthCheckUtility#3]
When entering the JSS URL in the utility, if you use the trailing slash such as "https://jss.acme.com:8443/" the utility will be unable to connect to the jss with an error of "Unable to connect or login to the JSS (see attached screenshot).
<img width="502" alt="screen shot 2016-03-21 at 10 01 23 am" src="https://cloud.githubusercontent.com/assets/877471/13920944/e9be1f48-ef4b-11e5-8d56-11dc377603c7.png">
 
But if you remove the slash, such as "https://jss.acme.com:8443" the utility will connect as expected.

**Comment by iamjake648** [comment]
This has been fixed, and will be included in the next beta. Thanks for the feedback!
